// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDL7cY_wGOrbEKU5FifqOtmRlswjVvQY',
    appId: '1:815269049643:web:250981a16b719e4738c16e',
    messagingSenderId: '815269049643',
    projectId: 'medicare-d6886',
    authDomain: 'medicare-d6886.firebaseapp.com',
    storageBucket: 'medicare-d6886.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBILHD0z9Wfo2KboxchGXQ_dge2EsJAXoc',
    appId: '1:815269049643:android:bf2ca805fcc0621838c16e',
    messagingSenderId: '815269049643',
    projectId: 'medicare-d6886',
    storageBucket: 'medicare-d6886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtn070NrpJ5CVe2q_m8vWAfQeBFwV5blw',
    appId: '1:815269049643:ios:0d7461c6ff21d17138c16e',
    messagingSenderId: '815269049643',
    projectId: 'medicare-d6886',
    storageBucket: 'medicare-d6886.appspot.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtn070NrpJ5CVe2q_m8vWAfQeBFwV5blw',
    appId: '1:815269049643:ios:d0736a5bfeac4f5f38c16e',
    messagingSenderId: '815269049643',
    projectId: 'medicare-d6886',
    storageBucket: 'medicare-d6886.appspot.com',
    iosBundleId: 'com.example.medicare.RunnerTests',
  );
}
